/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SamajdarshanRouteImport } from './routes/samajdarshan'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as KohliSamajRouteImport } from './routes/kohli-samaj'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as LiveEventsIndexRouteImport } from './routes/live-events.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as CommitteeIndexRouteImport } from './routes/committee.index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as ServicesSocioEconomicPortalRouteImport } from './routes/services.socio-economic-portal'
import { Route as SamajParichayTopicIdRouteImport } from './routes/samaj-parichay.$topicId'
import { Route as LiveEventsVideoIdRouteImport } from './routes/live-events.$videoId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as CommitteeMemberIdRouteImport } from './routes/committee.$memberId'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SamajdarshanRoute = SamajdarshanRouteImport.update({
  id: '/samajdarshan',
  path: '/samajdarshan',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const KohliSamajRoute = KohliSamajRouteImport.update({
  id: '/kohli-samaj',
  path: '/kohli-samaj',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const LiveEventsIndexRoute = LiveEventsIndexRouteImport.update({
  id: '/live-events/',
  path: '/live-events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeIndexRoute = CommitteeIndexRouteImport.update({
  id: '/committee/',
  path: '/committee/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSocioEconomicPortalRoute =
  ServicesSocioEconomicPortalRouteImport.update({
    id: '/socio-economic-portal',
    path: '/socio-economic-portal',
    getParentRoute: () => ServicesRoute,
  } as any)
const SamajParichayTopicIdRoute = SamajParichayTopicIdRouteImport.update({
  id: '/samaj-parichay/$topicId',
  path: '/samaj-parichay/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveEventsVideoIdRoute = LiveEventsVideoIdRouteImport.update({
  id: '/live-events/$videoId',
  path: '/live-events/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeMemberIdRoute = CommitteeMemberIdRouteImport.update({
  id: '/committee/$memberId',
  path: '/committee/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/kohli-samaj': typeof KohliSamajRoute
  '/notices': typeof NoticesRoute
  '/samajdarshan': typeof SamajdarshanRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/committee/$memberId': typeof CommitteeMemberIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/live-events/$videoId': typeof LiveEventsVideoIdRoute
  '/samaj-parichay/$topicId': typeof SamajParichayTopicIdRoute
  '/services/socio-economic-portal': typeof ServicesSocioEconomicPortalRoute
  '/books/': typeof BooksIndexRoute
  '/committee/': typeof CommitteeIndexRoute
  '/events/': typeof EventsIndexRoute
  '/live-events/': typeof LiveEventsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/kohli-samaj': typeof KohliSamajRoute
  '/notices': typeof NoticesRoute
  '/samajdarshan': typeof SamajdarshanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/committee/$memberId': typeof CommitteeMemberIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/live-events/$videoId': typeof LiveEventsVideoIdRoute
  '/samaj-parichay/$topicId': typeof SamajParichayTopicIdRoute
  '/services/socio-economic-portal': typeof ServicesSocioEconomicPortalRoute
  '/books': typeof BooksIndexRoute
  '/committee': typeof CommitteeIndexRoute
  '/events': typeof EventsIndexRoute
  '/live-events': typeof LiveEventsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/kohli-samaj': typeof KohliSamajRoute
  '/notices': typeof NoticesRoute
  '/samajdarshan': typeof SamajdarshanRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/committee/$memberId': typeof CommitteeMemberIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/live-events/$videoId': typeof LiveEventsVideoIdRoute
  '/samaj-parichay/$topicId': typeof SamajParichayTopicIdRoute
  '/services/socio-economic-portal': typeof ServicesSocioEconomicPortalRoute
  '/books/': typeof BooksIndexRoute
  '/committee/': typeof CommitteeIndexRoute
  '/events/': typeof EventsIndexRoute
  '/live-events/': typeof LiveEventsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/gallery'
    | '/kohli-samaj'
    | '/notices'
    | '/samajdarshan'
    | '/services'
    | '/sitemap.xml'
    | '/statistics'
    | '/books/$bookId'
    | '/committee/$memberId'
    | '/events/$eventId'
    | '/live-events/$videoId'
    | '/samaj-parichay/$topicId'
    | '/services/socio-economic-portal'
    | '/books/'
    | '/committee/'
    | '/events/'
    | '/live-events/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/gallery'
    | '/kohli-samaj'
    | '/notices'
    | '/samajdarshan'
    | '/sitemap.xml'
    | '/statistics'
    | '/books/$bookId'
    | '/committee/$memberId'
    | '/events/$eventId'
    | '/live-events/$videoId'
    | '/samaj-parichay/$topicId'
    | '/services/socio-economic-portal'
    | '/books'
    | '/committee'
    | '/events'
    | '/live-events'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/gallery'
    | '/kohli-samaj'
    | '/notices'
    | '/samajdarshan'
    | '/services'
    | '/sitemap.xml'
    | '/statistics'
    | '/books/$bookId'
    | '/committee/$memberId'
    | '/events/$eventId'
    | '/live-events/$videoId'
    | '/samaj-parichay/$topicId'
    | '/services/socio-economic-portal'
    | '/books/'
    | '/committee/'
    | '/events/'
    | '/live-events/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  KohliSamajRoute: typeof KohliSamajRoute
  NoticesRoute: typeof NoticesRoute
  SamajdarshanRoute: typeof SamajdarshanRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatisticsRoute: typeof StatisticsRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  CommitteeMemberIdRoute: typeof CommitteeMemberIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  LiveEventsVideoIdRoute: typeof LiveEventsVideoIdRoute
  SamajParichayTopicIdRoute: typeof SamajParichayTopicIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
  CommitteeIndexRoute: typeof CommitteeIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LiveEventsIndexRoute: typeof LiveEventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samajdarshan': {
      id: '/samajdarshan'
      path: '/samajdarshan'
      fullPath: '/samajdarshan'
      preLoaderRoute: typeof SamajdarshanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kohli-samaj': {
      id: '/kohli-samaj'
      path: '/kohli-samaj'
      fullPath: '/kohli-samaj'
      preLoaderRoute: typeof KohliSamajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/live-events/': {
      id: '/live-events/'
      path: '/live-events'
      fullPath: '/live-events/'
      preLoaderRoute: typeof LiveEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee/': {
      id: '/committee/'
      path: '/committee'
      fullPath: '/committee/'
      preLoaderRoute: typeof CommitteeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/socio-economic-portal': {
      id: '/services/socio-economic-portal'
      path: '/socio-economic-portal'
      fullPath: '/services/socio-economic-portal'
      preLoaderRoute: typeof ServicesSocioEconomicPortalRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/samaj-parichay/$topicId': {
      id: '/samaj-parichay/$topicId'
      path: '/samaj-parichay/$topicId'
      fullPath: '/samaj-parichay/$topicId'
      preLoaderRoute: typeof SamajParichayTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-events/$videoId': {
      id: '/live-events/$videoId'
      path: '/live-events/$videoId'
      fullPath: '/live-events/$videoId'
      preLoaderRoute: typeof LiveEventsVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee/$memberId': {
      id: '/committee/$memberId'
      path: '/committee/$memberId'
      fullPath: '/committee/$memberId'
      preLoaderRoute: typeof CommitteeMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesSocioEconomicPortalRoute: typeof ServicesSocioEconomicPortalRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSocioEconomicPortalRoute: ServicesSocioEconomicPortalRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  KohliSamajRoute: KohliSamajRoute,
  NoticesRoute: NoticesRoute,
  SamajdarshanRoute: SamajdarshanRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatisticsRoute: StatisticsRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  CommitteeMemberIdRoute: CommitteeMemberIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  LiveEventsVideoIdRoute: LiveEventsVideoIdRoute,
  SamajParichayTopicIdRoute: SamajParichayTopicIdRoute,
  BooksIndexRoute: BooksIndexRoute,
  CommitteeIndexRoute: CommitteeIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  LiveEventsIndexRoute: LiveEventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
